# Generated by Django 5.0.3 on 2024-03-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.IntegerField(blank=True, help_text='Phone Number')),
                ('query', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
