# Generated by Django 5.0.3 on 2024-03-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_image_url_alter_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='session_duration',
            field=models.IntegerField(help_text='Session duration in minutes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sessions',
            field=models.IntegerField(help_text='Number of sessions'),
        ),
    ]
